// <auto-generated />
using FeedbackProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FeedbackProject.Migrations
{
    [DbContext(typeof(FeedbackProjectContext))]
    [Migration("20200501200300_SeededTables")]
    partial class SeededTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FeedbackProject.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseName = "Java"
                        },
                        new
                        {
                            Id = 2,
                            CourseName = "Python"
                        },
                        new
                        {
                            Id = 3,
                            CourseName = "Javascrip"
                        },
                        new
                        {
                            Id = 4,
                            CourseName = "PHP"
                        });
                });

            modelBuilder.Entity("FeedbackProject.Models.FeedBack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeedbackWriterEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeedbackWriterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeachedCourseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeachedCourseId");

                    b.ToTable("Feedbacks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Feedback = "Totul a fost bine",
                            FeedbackWriterEmail = "a@a.com",
                            FeedbackWriterName = "Bogdan Tudorica",
                            TeachedCourseId = 1
                        },
                        new
                        {
                            Id = 2,
                            Feedback = "Nu totul a fost bine",
                            FeedbackWriterEmail = "b@b.com",
                            FeedbackWriterName = "Jan Constatin",
                            TeachedCourseId = 1
                        },
                        new
                        {
                            Id = 3,
                            Feedback = "Totul a fost bine",
                            FeedbackWriterEmail = "c@c.com",
                            FeedbackWriterName = "Lili Horinca",
                            TeachedCourseId = 2
                        },
                        new
                        {
                            Id = 4,
                            Feedback = "Nu totul a fost bine",
                            FeedbackWriterEmail = "d@d.com",
                            FeedbackWriterName = "Bogdan Sava",
                            TeachedCourseId = 2
                        },
                        new
                        {
                            Id = 5,
                            Feedback = "Nu totul a fost bine",
                            FeedbackWriterEmail = "c@c.com",
                            FeedbackWriterName = "Ioana Constatin",
                            TeachedCourseId = 3
                        });
                });

            modelBuilder.Entity("FeedbackProject.Models.TeachedCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeachedCourses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 2,
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 3,
                            TeacherId = 3
                        });
                });

            modelBuilder.Entity("FeedbackProject.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ab@feedback.com",
                            FirstName = "Alin",
                            LastName = "Bradut"
                        },
                        new
                        {
                            Id = 2,
                            Email = "lc@feedback.com",
                            FirstName = "Larisa",
                            LastName = "Costache"
                        },
                        new
                        {
                            Id = 3,
                            Email = "gt@feedback.com",
                            FirstName = "George",
                            LastName = "Trifan"
                        },
                        new
                        {
                            Id = 4,
                            Email = "on@feedback.com",
                            FirstName = "Ovidiu",
                            LastName = "Netoiu"
                        });
                });

            modelBuilder.Entity("FeedbackProject.Models.FeedBack", b =>
                {
                    b.HasOne("FeedbackProject.Models.TeachedCourse", "TeachedCourse")
                        .WithMany()
                        .HasForeignKey("TeachedCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FeedbackProject.Models.TeachedCourse", b =>
                {
                    b.HasOne("FeedbackProject.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FeedbackProject.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
